### ISSUE TITLE
Cant found type=gelf in freebsd 10.x 32/64bit

### ISSUE THREAD

**Issue by skythink** [emsearcy/fluent-plugin-gelf#19]
hi i have trouble when im clone source and copy to path plugin fluentd like documentation official, when im trying debug i have error still no have found type=gelf ??? what i've missing ? 

2016-09-21 08:26:43 +0700 [debug]: plugin/out_copy.rb:44:block in configure: adding store type="gelf"
2016-09-21 08:26:43 +0700 [error]: fluent/supervisor.rb:369:rescue in main_process: config error file="./fluent/fluent.conf" error="Unknown output plugin 'gelf'. Run 'gem search -rd fluent-plugin' to find plugins"

thanks

env : freebsd 10.x amd64
fluend v0.12 (install by gem)

**Comment by emsearcy** [comment]
I use td-agent on RHEL/CentOS and have the plugin in /etc/td-agent/plugin/out_gelf.rb.  I'm not sure where plugins go with a gem installation...

I'm assuming that merging #17 will let you install out_gelf as a gem which would make sense.  Can you help me test #17 by cloning https://github.com/cosmo0920/fluent-plugin-gelf/tree/add-gemspec and place it in path/to/ruby/gems/fluent-plugin-gelf-0.1.0/ and see if it then shows up in "gem search -rd fluent-plugin".  Thanks!

**Comment by emsearcy** [comment]
(If you're not sure where the gems/ path is, try finding where the other fluentd-plugin-* plugins are on your system.)

**Comment by skythink** [comment]
@emsearcy yea, you're right. im try to installin in debian or centos its no problem and works. when im try in freebsd 10.x im always have error like that. i see distribution unix not have package td-agent. alternative im compile by source to installing. im need module gelf for sent log to my graylog server. 

:)

**Comment by skythink** [comment]
@emsearcy  solved ! thanks for your suggest, im compile from reference your link and copy all lib to path ruby /usr/local/lib/ruby/gems/2.2/gems/ 

and output-gelf FOUND !!! 

thanks

**Comment by skythink** [comment]
thanks @emsearcy  ... im wrong definitions path library for save plugin in ruby.

**Comment by emsearcy** [comment]
As an aside, I just realized what the above problem was.  Installing this plugin in /etc/fluent/plugin or /etc/td-agent/plugin doesn't add the "gelf" library dependency.  You can install this manually by finding the path to fluent-gem and running "fluent-gem install gelf".

Switching to a gem installation of out_gelf probably just took care of the dependency for you.
