### ISSUE TITLE
undefined method `bytesize'

### ISSUE THREAD

**Issue by hnaiboglu** [emsearcy/fluent-plugin-gelf#27]
Hello @emsearcy,
I am getting the following error.

> 2016-11-29 16:33:07 +0300 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `bytesize' for nil:NilClass" tag="requests.domain"
>   2016-11-29 16:33:07 +0300 [warn]: suppressed same stacktrace
> 2016-11-29 16:33:07 +0300 [error]: forward error error=#<NoMethodError: undefined method `bytesize' for nil:NilClass> error_class=NoMethodError
>   2016-11-29 16:33:07 +0300 [error]: suppressed same stacktrace

@poom also commented about this here : https://github.com/emsearcy/fluent-plugin-gelf/commit/592a571fd089180f80db37f927f5f6788d3e2ee0

**Comment by shengis** [comment]
Hello, same here
```
2016-12-09 11:56:55 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `bytesize' for #<Hash:0x007fd349152038>" tag="kubernetes.var.log.containers.fluen
td-es-2x0tc_logs_fluentd-es-6a84670299e47030cbda1171b9ca4761e8aa48bfb8dd585c5f3ca442ef865e67.log"
```
