### ISSUE TITLE
Tagging and versioning

### ISSUE THREAD

**Issue by oogali** [emsearcy/fluent-plugin-gelf#31]
Hi,

Can you start generating Git tags that correspond with the versions you plan on releasing to Rubygems? (Thanks, for the new gemspec)

I'd like to be able to get a particular version of this repository... but without having to reference an entire Git commit hash.

I'm sorry if this sounds trivial, but it's the pattern I've come to expect from the majority of open-source projects I work with.

**Comment by emsearcy** [comment]
Great idea.

**Comment by cosmo0920** [comment]
My https://github.com/emsearcy/fluent-plugin-gelf/pull/17 introduced releasing management rake tasks which is named `release`.
`rake release` might be helpful.

**Comment by cosmo0920** [comment]
#17 is merged.
Could you release this gem into rubygems.org with the following command?

```
$ bundle execd rake release
```

**Comment by cosmo0920** [comment]
@emsearcy Any thoughts?

**Comment by cosmo0920** [comment]
ping?

**Comment by cosmo0920** [comment]
@emsearcy 
We want to make more easy to fluent-plugin-gelf installation.
In https://github.com/fluent/fluentd-docs/pull/587, we must install your plugin by hand.
It is very inconvenient for Fluentd users.... :sob:
