### ISSUE TITLE
Write does not fail when input is turned off.

### ISSUE THREAD

**Issue by rusia-rak** [emsearcy/fluent-plugin-gelf#33]
If my input is turned off to where fluentd is sending the chunks, fluentd doesn't retry the chunks and anyways if using buf_file, the file is deleted after flush_interval. I am assuming fluentd doen't mark the write as failed in this case and deletes the buffer file.

**Comment by emsearcy** [comment]
Can you try using TCP to connect to Graylog?
(protocol = tcp)

UDP is stateless (fire and forget) so there isn't any error checking to see if a GELF packet was received or not.

**Comment by rusia-rak** [comment]
yes, ultimately figured it out. Indeed udp wont work. 

Thanks :)
